createDesktopEntry: ENH: Allow checking with --check
For easier use in setup-software.

diff --git a/bin/createDesktopEntry b/bin/createDesktopEntry
--- a/bin/createDesktopEntry
+++ b/bin/createDesktopEntry
@@ -13,6 +13,7 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '-e|--exec COMMAND [-n|--name NAME] [-i|--icon ICON] [-c|--comment COMMENT] [-t|--category CATEGORY [-t ...]] [--autostart|-d|--destination DESTINATION-DIR] [-f|--force] DESKTOP-ENTRY [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--check ...'
 }
 printUsage()
 {
@@ -32,6 +33,8 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --check		Check whether DESKTOP-ENTRY (and ICON) already exist (by
+			name, ignoring the contents).
     --exec|-e COMMAND	Execute COMMAND; for a complete command-line or
 			environment variable expansion, wrap in sh -c "COMMAND"
     --name|-n NAME	Use NAME instead of deriving it from COMMAND.
@@ -54,9 +57,9 @@ RELATED COMMANDS:
   existing desktop entry
 
 EXIT STATUS:
-    0	Complete success.
+    0	Complete success / DESKTOP-ENTRY already exists.
     1	A DESKTOP-ENTRY already exists at the destination and no --force was
-	given.
+	given / DESKTOP-ENTRY or ICON do not exist yet.
     2	Bad invocation, wrong or missing command-line arguments.
     3	Internal error or failed assertion.
 HELPTEXT
@@ -70,10 +73,12 @@ typeset -a categoryList=()
 destinationDirspec=~/.local/share/applications
 isForce=
 autostart=
+isCheck=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--check)	shift; isCheck=t;;
 	--exec|-e)	shift; command="$1"; shift;;
 	--name|-n)	shift; name="$1"; shift;;
 	--icon|-i)	shift; icon="$1"; shift;;
@@ -107,10 +112,6 @@ fi >&2
 [ -n "$name" ] || name="$(commandName --no-interpreter --eval "$command")" || name="$command"
 
 desktopEntryFilespec="${destinationDirspec%/}/${desktopEntryName%.desktop}.desktop"
-if [ -e "$desktopEntryFilespec" ] && [ ! "$isForce" ]; then
-    printf >&2 'ERROR: Desktop entry already exists at: %s\n' "$desktopEntryFilespec"
-    exit 1
-fi
 
 iconFilespec=
 if [[ "$icon" =~ / ]]; then
@@ -120,6 +121,15 @@ if [[ "$icon" =~ / ]]; then
     fi
     iconFilespec="$icon"
     icon="$(basename -- "$icon")"
+fi
+
+if [ "$isCheck" ]; then
+    [ -e "$desktopEntryFilespec" ] || exit 1
+    [ -z "$iconFilespec" ] || addIcon --check -- "$iconFilespec" || exit 1
+    exit 0
+elif [ -e "$desktopEntryFilespec" ] && [ ! "$isForce" ]; then
+    printf >&2 'ERROR: Desktop entry already exists at: %s\n' "$desktopEntryFilespec"
+    exit 1
 fi
 
 saveIFS="$IFS"
