Renaming: Add "desktop" prefix to all template variables
And rename desktopEntryFilespec to targetFilespec.

diff --git a/bin/createDesktopEntry b/bin/createDesktopEntry
--- a/bin/createDesktopEntry
+++ b/bin/createDesktopEntry
@@ -66,14 +66,14 @@ EXIT STATUS:
 HELPTEXT
 }
 
-command=
-name=
-icon="$CREATEDESKTOPENTRY_DEFAULT_ICON"
-comment=
+desktopExec=
+desktopName=
+desktopIcon="$CREATEDESKTOPENTRY_DEFAULT_ICON"
+desktopComment=
 typeset -a categoryList=()
 destinationDirspec=~/.local/share/applications
 isForce=
-autostart=
+desktopAutostart=
 desktopEntryName=
 isCheck=
 while [ $# -ne 0 ]
@@ -81,12 +81,12 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--check)	shift; isCheck=t;;
-	--exec|-e)	shift; command="$1"; shift;;
-	--name|-n)	shift; name="$1"; shift;;
-	--icon|-i)	shift; icon="$1"; shift;;
-	--comment|-c)	shift; comment="$1"; shift;;
+	--exec|-e)	shift; desktopExec="$1"; shift;;
+	--name|-n)	shift; desktopName="$1"; shift;;
+	--icon|-i)	shift; desktopIcon="$1"; shift;;
+	--comment|-c)	shift; desktopComment="$1"; shift;;
 	--category|-t)	shift; categoryList+=("$1"); shift;;
-	--autostart)	shift; destinationDirspec=~/.config/autostart; autostart='X-GNOME-Autostart-enabled=true';;
+	--autostart)	shift; destinationDirspec=~/.config/autostart; desktopAutostart='X-GNOME-Autostart-enabled=true';;
 	--destination|-d)
 			shift; destinationDirspec="${1:?}"; shift;;
 	--force|-f)	shift; isForce=t;;
@@ -103,46 +103,46 @@ if [ $# -ne 0 ]; then
     printUsage "$0" >&2
     exit 2
 fi
-[ -n "$name" ] || name="$(commandName --no-interpreter --eval "$command")" || name="$command"
-: ${desktopEntryName:="${name:?}"}
+[ -n "$desktopName" ] || desktopName="$(commandName --no-interpreter --eval "$desktopExec")" || desktopName="$desktopExec"
+: ${desktopEntryName:="${desktopName:?}"}
 if [[ "$desktopEntryName" =~ / ]]; then
     echo 'ERROR: DESKTOP-ENTRY must be a pure name, not a path.'
     echo
     printUsage "$0"
     exit 2
-elif [ -z "$command" ]; then
-    echo 'ERROR: No -e|--exec COMMAND passed.'
+elif [ -z "$desktopExec" ]; then
+    echo 'ERROR: No -T|--template or -e|--exec COMMAND passed.'
     echo
     printUsage "$0"
     exit 2
 fi >&2
 
-desktopEntryFilespec="${destinationDirspec%/}/${desktopEntryName%.desktop}.desktop"
+targetFilespec="${destinationDirspec%/}/${desktopEntryName%.desktop}.desktop"
 
 iconFilespec=
-if [[ "$icon" =~ / ]]; then
-    if [ ! -r "$icon" ]; then
-	printf >&2 'ERROR: Icon does not exist at %s\n', "$icon"
+if [[ "$desktopIcon" =~ / ]]; then
+    if [ ! -r "$desktopIcon" ]; then
+	printf >&2 'ERROR: Icon does not exist at %s\n', "$desktopIcon"
 	exit 2
     fi
-    iconFilespec="$icon"
-    icon="$(basename -- "$icon")"
+    iconFilespec="$desktopIcon"
+    desktopIcon="$(basename -- "$desktopIcon")"
 fi
 
 if [ "$isCheck" ]; then
-    [ -e "$desktopEntryFilespec" ] || exit 1
+    [ -e "$targetFilespec" ] || exit 1
     [ -z "$iconFilespec" ] || addIcon --check -- "$iconFilespec" || exit 1
     exit 0
-elif [ -e "$desktopEntryFilespec" ] && [ ! "$isForce" ]; then
-    printf >&2 'ERROR: Desktop entry already exists at: %s\n' "$desktopEntryFilespec"
+elif [ -e "$targetFilespec" ] && [ ! "$isForce" ]; then
+    printf >&2 'ERROR: Desktop entry already exists at: %s\n' "$targetFilespec"
     exit 1
 fi
 
 saveIFS="$IFS"
-IFS=';'; categories="${categoryList[*]}"
+IFS=';'; desktopCategories="${categoryList[*]}"
 IFS="$saveIFS"
 
-export name comment command icon autostart categories
-shelltemplate --target "$desktopEntryFilespec" -- "$templateFilespec" || exit $?
+export desktopName desktopComment desktopExec desktopIcon desktopAutostart desktopCategories
+shelltemplate --target "$targetFilespec" -- "$templateFilespec" || exit $?
 
 [ -z "$iconFilespec" ] || acceptStatus 0 4 99 -- addIcon --copy ${isForce:+--force} -- "$iconFilespec"
